version: '3.1'

services:

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example
    volumes:
            - ../leetcode-sql:/root/leetcode-sql/
    ports:
        - "5432:5432"

